"""corrigir update_at

Revision ID: 54f30f2be4cd
Revises: e7b6da74ee46
Create Date: 2025-01-09 17:06:40.253332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54f30f2be4cd'
down_revision: Union[str, None] = 'e7b6da74ee46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
